apiVersion: v1
kind: Service
metadata:
  name: salary-regression
spec:
  type: LoadBalancer
  selector:
    app: salary-regression
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000