apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  type: LoadBalancer  # or NodePort for local clusters
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
