apiVersion: v1
kind: Service
metadata:
  name: churnmodelling
spec:
  type: LoadBalancer
  selector:
    app: churnmodelling
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8000